import type { Streamer, MockUser, ChatMessage, Gift, DiamondPackage, PastLive, Medal, VideoPost, VideoComment, PhotoPost, ContentPost, Conversation } from './types';

export const STREAMERS_DATA: Streamer[] = [
  {
    id: 1,
    name: 'validando',
    title: 'validando ✨',
    avatarUrl: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    streamImageUrl: 'https://images.pexels.com/photos/1758144/pexels-photo-1758144.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=1',
    streamVideoUrl: 'https://videos.pexels.com/video-files/8327711/8327711-hd_1080_1920_25fps.mp4',
    viewers: 229,
    points: '799',
    isVs: false,
    isNew: false,
    specialIcon: 'snowflake',
    specialIconColor: 'text-cyan-400',
    isLocked: false,
    lockPrice: 0,
    followedByCurrentUser: true,
    followers: 6440,
    following: 79,
    gender: 'Feminino',
    birthday: '10/01/2005',
    location: 'Brasil',
    distance: 1697.48,
    sentDiamonds: 3,
    isLive: true,
    isVerified: true,
    lastLive: 'agora',
  },
  {
    id: 2,
    name: 'Estrellita',
    title: 'sigo você 🌹',
    avatarUrl: 'https://picsum.photos/seed/2/100/100',
    streamImageUrl: 'https://images.pexels.com/photos/3772510/pexels-photo-3772510.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=1',
    streamVideoUrl: 'https://videos.pexels.com/video-files/7578542/7578542-hd_1080_1920_25fps.mp4',
    viewers: 2598,
    points: '1400000',
    isVs: false,
    isNew: true,
    specialIcon: 'moon',
    specialIconColor: 'text-yellow-300',
    isLocked: true,
    lockPrice: 20,
    followedByCurrentUser: true,
    followers: 890000,
    following: 201,
    gender: 'Feminino',
    birthday: '05/03/2002',
    location: 'Brasil',
    distance: 8500,
    sentDiamonds: 150,
    isLive: false,
    isVerified: false,
    lastLive: 'há 2 horas',
  },
  {
    id: 3,
    name: 'Lilibeth',
    title: '2 🌹 sigo',
    avatarUrl: 'https://picsum.photos/seed/3/100/100',
    streamImageUrl: 'https://images.pexels.com/photos/1848565/pexels-photo-1848565.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=1',
    streamVideoUrl: 'https://videos.pexels.com/video-files/8470355/8470355-hd_1080_1920_30fps.mp4',
    viewers: 5114,
    points: '2500000',
    isVs: false,
    isNew: false,
    specialIcon: 'flower',
    specialIconColor: 'text-pink-400',
    isLocked: false,
    lockPrice: 0,
    followedByCurrentUser: true,
    followers: 2100000,
    following: 50,
    location: 'Brasil',
    isLive: true,
    isVerified: true,
    lastLive: 'agora',
  },
  {
    id: 4,
    name: 'MARIÁH',
    title: 'Miss BUZZCAST',
    avatarUrl: 'https://picsum.photos/seed/4/100/100',
    streamImageUrl: 'https://images.pexels.com/photos/1193942/pexels-photo-1193942.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=1',
    streamVideoUrl: 'https://videos.pexels.com/video-files/7650036/7650036-hd_1080_1920_25fps.mp4',
    viewers: 5658,
    points: '2500000',
    isVs: false,
    isNew: false,
    specialIcon: 'star',
    specialIconColor: 'text-yellow-400',
    isLocked: true,
    lockPrice: 50,
    followedByCurrentUser: false,
    followers: 53000,
    following: 890,
    location: 'Brasil',
    isLive: false,
    isVerified: true,
    lastLive: 'ontem',
  },
  {
    id: 5,
    name: 'Sweetie',
    title: '2🌹= sigo de volta 8k ajuda me bater m...',
    avatarUrl: 'https://picsum.photos/seed/5/100/100',
    streamImageUrl: 'https://images.pexels.com/photos/2531553/pexels-photo-2531553.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=1',
    streamVideoUrl: 'https://videos.pexels.com/video-files/8065551/8065551-hd_1080_1920_25fps.mp4',
    viewers: 2515,
    points: '987000',
    isVs: true,
    isNew: false,
    specialIcon: null,
    specialIconColor: '',
    isLocked: false,
    lockPrice: 0,
    followedByCurrentUser: false,
    followers: 450000,
    following: 123,
    location: 'Brasil',
    isLive: true,
    isVerified: false,
    lastLive: 'agora',
  },
  {
    id: 6,
    name: 'Luna',
    title: 'Boa noite 🥰',
    avatarUrl: 'https://picsum.photos/seed/6/100/100',
    streamImageUrl: 'https://images.pexels.com/photos/1484806/pexels-photo-1484806.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=1',
    streamVideoUrl: 'https://videos.pexels.com/video-files/7148895/7148895-hd_1080_1920_25fps.mp4',
    viewers: 5148,
    points: '3100000',
    isVs: true,
    isNew: false,
    specialIcon: 'moon',
    specialIconColor: 'text-yellow-300',
    isLocked: false,
    lockPrice: 0,
    followedByCurrentUser: false,
    followers: 3500000,
    following: 88,
    location: 'Brasil',
    isLive: true,
    isVerified: true,
    lastLive: 'agora',
  },
  {
    id: 7,
    name: 'Aurora',
    title: 'Vem conversar',
    avatarUrl: 'https://picsum.photos/seed/7/100/100',
    streamImageUrl: 'https://images.pexels.com/photos/3771836/pexels-photo-3771836.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=1',
    streamVideoUrl: 'https://videos.pexels.com/video-files/7578964/7578964-hd_1080_1920_25fps.mp4',
    viewers: 800,
    points: '550000',
    isVs: false,
    isNew: true,
    specialIcon: 'star',
    specialIconColor: 'text-yellow-400',
    isLocked: false,
    lockPrice: 0,
    followedByCurrentUser: false,
    followers: 22000,
    following: 410,
    location: 'Brasil',
    isLive: false,
    isVerified: false,
    lastLive: 'há 5 horas',
  },
  {
    id: 8,
    name: 'Sofia',
    title: 'Jogando um pouco',
    avatarUrl: 'https://picsum.photos/seed/8/100/100',
    streamImageUrl: 'https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=1',
    streamVideoUrl: 'https://videos.pexels.com/video-files/4434250/4434250-hd_1080_1920_25fps.mp4',
    viewers: 152,
    points: '4200000',
    isVs: false,
    isNew: false,
    specialIcon: 'flower',
    specialIconColor: 'text-pink-400',
    isLocked: false,
    lockPrice: 0,
    followedByCurrentUser: false,
    followers: 5000000,
    following: 12,
    location: 'Brasil',
    isLive: false,
    isVerified: false,
    lastLive: 'há 1 dia',
  },
   {
    id: 9,
    name: 'Crystal',
    title: 'Bora bater a meta!',
    avatarUrl: 'https://picsum.photos/seed/9/100/100',
    streamImageUrl: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=1',
    streamVideoUrl: 'https://videos.pexels.com/video-files/8043963/8043963-hd_1080_1920_25fps.mp4',
    viewers: 990,
    points: '1800000',
    isVs: false,
    isNew: true,
    specialIcon: 'snowflake',
    specialIconColor: 'text-cyan-400',
    isLocked: true,
    lockPrice: 100,
    followedByCurrentUser: false,
    followers: 1900000,
    following: 300,
    location: 'Brasil',
    isLive: true,
    isVerified: false,
    lastLive: 'agora',
  },
   {
    id: 10,
    name: 'Ruby',
    title: 'Só diversão',
    avatarUrl: 'https://picsum.photos/seed/10/100/100',
    streamImageUrl: 'https://images.pexels.com/photos/277667/pexels-photo-277667.jpeg?auto=compress&cs=tinysrgb&w=400&h=600&dpr=1',
    streamVideoUrl: 'https://videos.pexels.com/video-files/4784093/4784093-hd_1080_1920_25fps.mp4',
    viewers: 420,
    points: '812000',
    isVs: true,
    isNew: true,
    specialIcon: null,
    specialIconColor: '',
    isLocked: false,
    lockPrice: 0,
    followedByCurrentUser: false,
    followers: 650000,
    following: 500,
    location: 'Brasil',
    isLive: false,
    isVerified: false,
    lastLive: 'há 8 horas',
  }
];

export const MOCK_FANS: MockUser[] = Array.from({ length: 20 }, (_, i) => ({
    id: 1000 + i,
    name: `FanUser${i + 1}`,
    avatarUrl: `https://picsum.photos/seed/fan${i}/100/100`,
    isFollowed: Math.random() > 0.5,
    followers: Math.floor(Math.random() * 1000),
    following: Math.floor(Math.random() * 500),
    points: `${Math.floor(Math.random() * 10000)}`,
    streamImageUrl: `https://picsum.photos/seed/fanbanner${i}/400/600`,
}));

export const MOCK_FOLLOWING: MockUser[] = Array.from({ length: 15 }, (_, i) => ({
    id: 2000 + i,
    name: `FollowedStreamer${i + 1}`,
    avatarUrl: `https://picsum.photos/seed/followed${i}/100/100`,
    isFollowed: true,
    followers: Math.floor(Math.random() * 50000),
    following: Math.floor(Math.random() * 200),
    points: `${Math.floor(Math.random() * 500000)}`,
    streamImageUrl: `https://picsum.photos/seed/followedbanner${i}/400/600`,
}));

export const MOCK_BLOCKED_USERS: MockUser[] = [
  { id: 4001, name: 'agataa20✨', avatarUrl: 'https://images.pexels.com/photos/1382731/pexels-photo-1382731.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1', isFollowed: false, followers: 0, following: 0, points: '0', streamImageUrl: '' },
  { id: 4002, name: 'Daniel21411894', avatarUrl: '', isFollowed: false, followers: 0, following: 0, points: '0', streamImageUrl: '' }, // Special case handled in component
  { id: 4003, name: 'João Gonçalves ⚡️', avatarUrl: 'https://images.pexels.com/photos/2531553/pexels-photo-2531553.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1', isFollowed: false, followers: 0, following: 0, points: '0', streamImageUrl: '' },
  { id: 4004, name: 'Isinhaa 🍑', avatarUrl: 'https://images.pexels.com/photos/3772510/pexels-photo-3772510.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1', isFollowed: false, followers: 0, following: 0, points: '0', streamImageUrl: '' },
  { id: 4005, name: 'PXCASAL', avatarUrl: 'https://images.pexels.com/photos/1484806/pexels-photo-1484806.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1', isFollowed: false, followers: 0, following: 0, points: '0', streamImageUrl: '' },
  { id: 4006, name: 'Casalvirado 🔥👄💥', avatarUrl: 'https://images.pexels.com/photos/1193942/pexels-photo-1193942.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1', isFollowed: false, followers: 0, following: 0, points: '0', streamImageUrl: '' },
  { id: 4007, name: 'sorriso congat', avatarUrl: 'https://images.pexels.com/photos/3771836/pexels-photo-3771836.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1', isFollowed: false, followers: 0, following: 0, points: '0', streamImageUrl: '' },
  { id: 4008, name: 'Lux Lariel 💅🏻💋', avatarUrl: 'https://images.pexels.com/photos/1848565/pexels-photo-1848565.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1', isFollowed: false, followers: 0, following: 0, points: '0', streamImageUrl: '' },
  { id: 4009, name: 'karynna leite', avatarUrl: 'https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1', isFollowed: false, followers: 0, following: 0, points: '0', streamImageUrl: '' },
  { id: 4010, name: 'casa? fuego💸🔥', avatarUrl: 'https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1', isFollowed: false, followers: 0, following: 0, points: '0', streamImageUrl: '' },
  { id: 4011, name: 'Fatima Gomes65', avatarUrl: 'https://images.pexels.com/photos/277667/pexels-photo-277667.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1', isFollowed: false, followers: 0, following: 0, points: '0', streamImageUrl: '' },
  { id: 4012, name: '🟣nubank🟣', avatarUrl: '', isFollowed: false, followers: 0, following: 0, points: '0', streamImageUrl: '' }, // Special case
  { id: 4013, name: 'Miiaa 🍑👏🍑👏', avatarUrl: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1', isFollowed: false, followers: 0, following: 0, points: '0', streamImageUrl: '' },
];


export const CHAT_MOCK_USERS: MockUser[] = [
    { id: 3001, name: 'Jalin Rabey', avatarUrl: 'https://picsum.photos/seed/user1/50/50', isFollowed: true, followers: 123, following: 45, points: '5821', streamImageUrl: 'https://picsum.photos/seed/userbanner1/400/600' },
    { id: 3002, name: 'Angelito', avatarUrl: 'https://picsum.photos/seed/user2/50/50', isFollowed: false, followers: 5, following: 12, points: '120', streamImageUrl: 'https://picsum.photos/seed/userbanner2/400/600' },
    { id: 3003, name: 'im singl boy', avatarUrl: 'https://picsum.photos/seed/user3/50/50', isFollowed: false, followers: 1, following: 88, points: '50', streamImageUrl: 'https://picsum.photos/seed/userbanner3/400/600' },
    { id: 3004, name: 'Userrrrrr', avatarUrl: 'https://picsum.photos/seed/user4/50/50', isFollowed: true, followers: 987, following: 123, points: '12845', streamImageUrl: 'https://picsum.photos/seed/userbanner4/400/600' },
    { id: 3005, name: 'GamerX', avatarUrl: 'https://picsum.photos/seed/user5/50/50', isFollowed: false, followers: 1500, following: 2, points: '32000', streamImageUrl: 'https://picsum.photos/seed/userbanner5/400/600' },
    { id: 3006, name: 'MusicLover', avatarUrl: 'https://picsum.photos/seed/user6/50/50', isFollowed: false, followers: 42, following: 15, points: '630', streamImageUrl: 'https://picsum.photos/seed/userbanner6/400/600' },
    ...Array.from({ length: 44 }, (_, i) => ({
        id: 3007 + i,
        name: `User${100 + i}`,
        avatarUrl: `https://i.pravatar.cc/50?u=user${100+i}`,
        isFollowed: Math.random() > 0.8,
        followers: Math.floor(Math.random() * 100),
        following: Math.floor(Math.random() * 50),
        points: `${Math.floor(Math.random() * 1000)}`,
        streamImageUrl: `https://picsum.photos/seed/chatuserbanner${i}/400/600`,
    })),
];

export const GIFTS: Gift[] = [
    { id: 1, name: 'Estrela', image: 'https://3dicons.sgp1.cdn.digitaloceanspaces.com/v1/png/rgb/star-2_rgb.png', cost: 3 },
    { id: 2, name: 'Estrela Roxa', image: 'https://3dicons.sgp1.cdn.digitaloceanspaces.com/v1/png/rgb/star-3_rgb.png', cost: 5 },
    { id: 3, name: 'Girassol', image: 'https://3dicons.sgp1.cdn.digitaloceanspaces.com/v1/png/rgb/flower_rgb.png', cost: 7 },
    { id: 4, name: 'Tigre', image: 'https://3dicons.sgp1.cdn.digitaloceanspaces.com/v1/png/rgb/cat-2_rgb.png', cost: 9 },
    { id: 5, name: 'Arco-íris', image: 'https://3dicons.sgp1.cdn.digitaloceanspaces.com/v1/png/rgb/rainbow_rgb.png', cost: 5 },
    { id: 6, name: 'Alvo', image: 'https://3dicons.sgp1.cdn.digitaloceanspaces.com/v1/png/rgb/ufo_rgb.png', cost: 11 },
    { id: 7, name: 'Coração', image: 'https://3dicons.sgp1.cdn.digitaloceanspaces.com/v1/png/rgb/box-2_rgb.png', cost: 19 },
    { id: 8, name: 'Roda Gigante', image: 'https://3dicons.sgp1.cdn.digitaloceanspaces.com/v1/png/rgb/ferris-wheel_rgb.png', cost: 29 },
];


export const INITIAL_MESSAGES: ChatMessage[] = [
    { id: 1, user: CHAT_MOCK_USERS[0], type: 'message', content: 'Memoria boa pra essas coisas' },
    { id: 2, user: CHAT_MOCK_USERS[1], type: 'gift', content: `enviou um(a) ${GIFTS[7].name}!`, gift: GIFTS[7] },
    { id: 3, user: CHAT_MOCK_USERS[1], type: 'follow', content: 'Novo seguidor!' },
    { id: 4, user: CHAT_MOCK_USERS[2], type: 'follow', content: 'Novo seguidor!' },
    { id: 5, user: CHAT_MOCK_USERS[3], type: 'message', content: 'Qual é tua mão direita?' },
];

export const DIAMOND_PACKAGES: DiamondPackage[] = [
    { diamonds: 600, price: 6.49, isMostSold: true },
    { diamonds: 3000, price: 32.99 },
    { diamonds: 6000, price: 64.99 },
    { diamonds: 18000, price: 194.99 },
    { diamonds: 36000, price: 388.99 },
    { diamonds: 60000, price: 649.99 },
];


export const MOCK_PAST_LIVES: PastLive[] = [
    {
        id: 'live1',
        title: 'Jogando com a galera!',
        date: '2 dias atrás',
        duration: '2h 15m',
        diamondsEarned: 15200,
        peakViewers: 1200,
        thumbnailUrl: 'https://images.pexels.com/photos/789822/pexels-photo-789822.jpeg?auto=compress&cs=tinysrgb&w=400',
    },
    {
        id: 'live2',
        title: 'Sessão de Q&A',
        date: '5 dias atrás',
        duration: '1h 30m',
        diamondsEarned: 8900,
        peakViewers: 850,
        thumbnailUrl: 'https://images.pexels.com/photos/4050315/pexels-photo-4050315.jpeg?auto=compress&cs=tinysrgb&w=400',
    },
     {
        id: 'live3',
        title: 'Vem conversar!',
        date: '1 semana atrás',
        duration: '3h 05m',
        diamondsEarned: 25600,
        peakViewers: 2300,
        thumbnailUrl: 'https://images.pexels.com/photos/4050303/pexels-photo-4050303.jpeg?auto=compress&cs=tinysrgb&w=400',
    },
];

export const MOCK_MEDALS: Medal[] = [
    {
        id: 'medal1',
        name: 'Streamer de Primeira',
        description: 'Realizou sua primeira transmissão ao vivo.',
        icon: 'VideoIcon',
        achieved: true,
        achievedDate: '20/07/2024',
        isNew: true,
    },
    {
        id: 'medal2',
        name: 'Coração Generoso',
        description: 'Enviou seu primeiro presente para um streamer.',
        icon: 'GiftIcon',
        achieved: true,
        achievedDate: '21/07/2024',
    },
    {
        id: 'medal3',
        name: 'Popular',
        description: 'Alcançou 1.000 seguidores.',
        icon: 'UsersIcon',
        achieved: true,
        achievedDate: '25/07/2024',
    },
    {
        id: 'medal4',
        name: 'Top Doador',
        description: 'Ficou no Top 3 de doadores de uma live.',
        icon: 'CrownIcon',
        achieved: false,
    },
     {
        id: 'medal5',
        name: 'Maratonista',
        description: 'Realizou uma transmissão por mais de 4 horas.',
        icon: 'ClockIcon',
        achieved: false,
    },
     {
        id: 'medal6',
        name: 'Verificado',
        description: 'Recebeu o selo de conta verificada.',
        icon: 'ShieldCheckIcon',
        achieved: true,
        isNew: true,
        achievedDate: '28/07/2024',
    }
];

export const MOCK_VIDEOS: VideoPost[] = [
    {
        id: 'vid1',
        type: 'video',
        user: STREAMERS_DATA[0],
        videoUrl: 'https://videos.pexels.com/video-files/853824/853824-hd_720_1366_25fps.mp4',
        description: 'Um dia na praia! ☀️🌊 #verao #praia #viagem',
        song: 'Som Original - @validando',
        likes: 1200000,
        comments: 4500,
        shares: 12500
    },
    {
        id: 'vid2',
        type: 'video',
        user: STREAMERS_DATA[1],
        videoUrl: 'https://videos.pexels.com/video-files/3254009/3254009-hd_720_1366_25fps.mp4',
        description: 'Meu setup novo! O que acharam? 💻✨ #gamer #setup #tecnologia',
        song: 'lofi hip hop - beats to relax/study to',
        likes: 895000,
        comments: 7200,
        shares: 18000
    },
    {
        id: 'vid3',
        type: 'video',
        user: STREAMERS_DATA[2],
        videoUrl: 'https://videos.pexels.com/video-files/3840441/3840441-hd_720_1366_24fps.mp4',
        description: 'Receita de bolo de chocolate super fácil! 🍰🍫 #receita #bolo #chocolate',
        song: 'Happy Upbeat - Background Music',
        likes: 2300000,
        comments: 11500,
        shares: 25000
    },
    {
        id: 'vid4',
        type: 'video',
        user: STREAMERS_DATA[5],
        videoUrl: 'https://videos.pexels.com/video-files/4904495/4904495-hd_720_1366_25fps.mp4',
        description: 'Dança nova do app! Quem consegue fazer? 💃🕺 #challenge #dança',
        song: 'Trending Song 2024 - Official Audio',
        likes: 3100000,
        comments: 22000,
        shares: 42000
    },
    {
        id: 'vid5',
        type: 'video',
        user: STREAMERS_DATA[8],
        videoUrl: 'https://videos.pexels.com/video-files/4057840/4057840-hd_720_1366_25fps.mp4',
        description: 'Pintando um novo quadro. Processo relaxante. 🎨 #arte #pintura #relax',
        song: 'Acoustic Guitar - Relaxing Music',
        likes: 550000,
        comments: 3200,
        shares: 8000
    }
];

export const MOCK_PHOTO_POSTS: PhotoPost[] = [
    {
        id: 'photo1',
        type: 'photo',
        user: STREAMERS_DATA[3],
        imageUrl: 'https://images.pexels.com/photos/3771836/pexels-photo-3771836.jpeg?auto=compress&cs=tinysrgb&w=800',
        description: 'Amo meu cantinho de leitura 📚 #livros #paz',
        likes: 78000,
        comments: 1200,
        shares: 2300
    },
    {
        id: 'photo2',
        type: 'photo',
        user: STREAMERS_DATA[4],
        imageUrl: 'https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=800',
        description: 'Look do dia ✨ #ootd #fashion',
        likes: 152000,
        comments: 3400,
        shares: 5600
    },
     {
        id: 'photo3',
        type: 'photo',
        user: STREAMERS_DATA[0],
        imageUrl: 'https://images.pexels.com/photos/33109/fall-autumn-red-season.jpg?auto=compress&cs=tinysrgb&w=800',
        description: 'As cores do outono são as mais bonitas! 🍂🍁',
        likes: 95000,
        comments: 2100,
        shares: 4100
    }
];

export const MOCK_CONTENT_POSTS: ContentPost[] = [...MOCK_VIDEOS, ...MOCK_PHOTO_POSTS].sort((a,b) => b.likes - a.likes);

export const MOCK_COMMENTS: VideoComment[] = Array.from({ length: 50 }, (_, i) => ({
    id: `comment${i}`,
    user: CHAT_MOCK_USERS[i % CHAT_MOCK_USERS.length], // reuse chat users
    text: `Comentário de exemplo número ${i + 1}. Muito legal! 👍`,
    likes: Math.floor(Math.random() * 500),
    timestamp: `${Math.floor(Math.random() * 59) + 1}m atrás`
}));

const CURRENT_USER_MOCK: MockUser = {
  id: 987654321,
  name: 'Usuário Teste',
  avatarUrl: 'https://picsum.photos/seed/user/200/200',
  isFollowed: true,
  followers: 0,
  following: 0,
  points: '0',
  streamImageUrl: '',
};

export const MOCK_CONVERSATIONS: Conversation[] = [
    {
        user: { ...STREAMERS_DATA[1], isFollowed: STREAMERS_DATA[1].followedByCurrentUser },
        lastMessage: "Ok, estarei lá! Não se atrase. 😉",
        timestamp: "14:32",
        unreadCount: 2,
        isMuted: false,
        isPinned: true,
    },
    {
        user: { ...STREAMERS_DATA[3], isFollowed: STREAMERS_DATA[3].followedByCurrentUser },
        lastMessage: "Você viu o novo filme? Foi incrível!",
        timestamp: "11:05",
        unreadCount: 0,
        isMuted: false,
        isPinned: true,
    },
    {
        user: { ...STREAMERS_DATA[0], isFollowed: STREAMERS_DATA[0].followedByCurrentUser },
        lastMessage: "Você: Vamos jogar hoje à noite?",
        timestamp: "Ontem",
        unreadCount: 0,
        isMuted: true,
    },
    {
        user: CHAT_MOCK_USERS[4],
        lastMessage: "Valeu pela ajuda no jogo!",
        timestamp: "Ontem",
        unreadCount: 5,
        isMuted: false,
    },
    {
        user: { ...STREAMERS_DATA[2], isFollowed: STREAMERS_DATA[2].followedByCurrentUser },
        lastMessage: "Foto enviada.",
        timestamp: "Sexta",
        unreadCount: 0,
        isMuted: false,
    },
    {
        user: CHAT_MOCK_USERS[1],
        lastMessage: "Até mais!",
        timestamp: "Quinta",
        unreadCount: 0,
        isMuted: false,
    },
    {
        user: CHAT_MOCK_USERS[2],
        lastMessage: "kkkkkkk",
        timestamp: "03/07",
        unreadCount: 0,
        isMuted: false,
    },
    {
        user: { ...STREAMERS_DATA[5], isFollowed: STREAMERS_DATA[5].followedByCurrentUser },
        lastMessage: "Você: Ótima live hoje!",
        timestamp: "01/07",
        unreadCount: 0,
        isMuted: false,
    },
];

export const MOCK_CHAT_HISTORY: { [key: number]: ChatMessage[] } = {
  [STREAMERS_DATA[1].id]: [
    { id: 1, user: { ...STREAMERS_DATA[1], isFollowed: STREAMERS_DATA[1].followedByCurrentUser }, type: 'message', content: "Oi, tudo bem? Vi que você me seguiu!" },
    { id: 2, user: CURRENT_USER_MOCK, type: 'message', content: "Oie! Tudo sim e com vc? Sim, adoro suas lives!" },
    { id: 3, user: { ...STREAMERS_DATA[1], isFollowed: STREAMERS_DATA[1].followedByCurrentUser }, type: 'message', content: "Que bom! Fico feliz 😊" },
    { id: 4, user: { ...STREAMERS_DATA[1], isFollowed: STREAMERS_DATA[1].followedByCurrentUser }, type: 'message', content: "Vou entrar ao vivo mais tarde, umas 20h. Aparece lá!" },
    { id: 5, user: CURRENT_USER_MOCK, type: 'message', content: "Fechado! Estarei lá." },
    { id: 6, user: { ...STREAMERS_DATA[1], isFollowed: STREAMERS_DATA[1].followedByCurrentUser }, type: 'message', content: "Ok, estarei lá! Não se atrase. 😉" },
  ],
  [STREAMERS_DATA[3].id]: [
    { id: 1, user: CURRENT_USER_MOCK, type: 'message', content: "E aí, MARIÁH!" },
    { id: 2, user: { ...STREAMERS_DATA[3], isFollowed: STREAMERS_DATA[3].followedByCurrentUser }, type: 'message', content: "Oii! Quem é vivo sempre aparece hahaha" },
    { id: 3, user: CURRENT_USER_MOCK, type: 'message', content: "Haha pois é! Correria... Mas e aí, viu o novo filme do Aranha?" },
    { id: 4, user: { ...STREAMERS_DATA[3], isFollowed: STREAMERS_DATA[3].followedByCurrentUser }, type: 'message', content: "Você viu o novo filme? Foi incrível!" },
  ],
  [STREAMERS_DATA[0].id]: [
      { id: 1, user: CURRENT_USER_MOCK, type: 'message', content: "Vamos jogar hoje à noite?" },
  ],
  [CHAT_MOCK_USERS[4].id]: [
      { id: 1, user: CHAT_MOCK_USERS[4], type: 'message', content: "Eaeee" },
      { id: 2, user: CHAT_MOCK_USERS[4], type: 'message', content: "Valeu pela ajuda no jogo!" },
  ]
};